# services is a version 2 only feature
version: '2'

services:
  server:
    image: "mesoform/concierge-squid-gcp-proxy:0.1.0"
    domainname: "squid-gcp-proxy.gcp.mesoform.com"
    restart: always
    mem_limit: 128m
    dns: 127.0.0.1
    command: /usr/sbin/squid3 -f /etc/squid-gcp-proxy/squid.conf
    ports:
      - 3128
      - 8301/udp
      - 8301/tcp
      - 8300/tcp
      - 8400
      - 8302/udp
      - 8302/tcp
      - 8500
      - 10050
    environment:
      - SVC_DISCOVERY=consul
      - CHANGE_ME=3
