# services is a version 2 only feature
# Container Orchestration for a Concierge Managed Application
# http://www.mesoform.com/blog-listing/info/the-concierge-paradigm

version: '2.1'

services:
  squid-gcp-proxy:
    image: "mesoform/concierge-squid-gcp-proxy:0.1.0"
    domainname: "squid-gcp-proxy.gcp.mesoform.com"
    dns_search:
      - squid-gcp-proxy.gcp.mesoform.com
      - svc.ops.mesoform-services.com
    labels:
      - triton.cns.services=squid-gcp-proxy
    restart: always
    mem_limit: 128m
    ## For Triton bridge mode needs explicitly setting because the docker compose client
    ## sends network_mode=default by default. The uncommenting of this line is handled
    ## in the Ansible code but can obviously be uncommented personally for manual interaction
    # network_mode: bridge
    # Triton also doesn't handle domain_name, so we fix this by adding a
    # DNS_DOMAIN=squid-gcp-proxy.gcp.mesoform.com environment variable below
    depends_on:
      - consul
    ports:
      - 3128
      - 10050
    ## uncomment to test your application start without containerpilot
    #entrypoint: /usr/sbin/squid3 -N -f /etc/squid-gcp-proxy/squid.conf
